# Generated by Django 5.1.1 on 2024-09-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_service_abn_service_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
