# Generated by Django 5.1.1 on 2024-09-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_provider',
            field=models.CharField(max_length=255),
        ),
    ]
